todoInfo:
  Type: "AWS::DynamoDB::Table"
  Properties:
    AttributeDefinitions:
      - AttributeName: "todoId"
        AttributeType: "S" 
      - AttributeName: "title"
        AttributeType: "S"   
      - AttributeName: "creationDate"
        AttributeType: "S"        
                  
    KeySchema:
      - AttributeName: "todoId"
        KeyType: "HASH"
      - AttributeName: "creationDate"
        KeyType: "RANGE"
    ProvisionedThroughput:
      ReadCapacityUnits: "5"
      WriteCapacityUnits: "5"
    TableName: "DBT_TODO_INFO_2"
    LocalSecondaryIndexes:
      - IndexName: "LSI_title"
        KeySchema:
          - AttributeName: "todoId"
            KeyType: "HASH"
          - AttributeName: "title"
            KeyType: "RANGE"
        Projection:
          ProjectionType: "ALL"

